### ISSUE TITLE
[Q] How to set validationConstraints?

### ISSUE THREAD

**Issue by JackQiang888** [bizley/yii2-jwt#14]
1 how to set value to validationConstraints? can you give a sample?
2 set the validationConstraints to componensts as this?

> 

 'jwt' => [
            'class' =>  bizley\jwt\Jwt::class,
            'signer' => bizley\jwt\Jwt::RS256,
            'signingKey' => '',
            'verifyingKey' => [
                'key' => @'pubkey.pem', /* key content */
                'passphrase' => '',  /* key passphrase */
                'store' => bizley\jwt\Jwt::STORE_IN_MEMORY, /* storage type */
                'method' => bizley\jwt\Jwt::METHOD_FILE /* method type */
            ],
            'validationConstraints'=> [
            **************************
            ]
        ],

**Comment by bizley** [comment]
Like this for example:

```
'validationConstraints' => [
    new \Lcobucci\JWT\Validation\Constraint\LooseValidAt(
        new \Lcobucci\Clock\SystemClock(new \DateTimeZone(/* your timezone here */)),
        new \DateInterval('PT1M')
    ),
    new \Lcobucci\JWT\Validation\Constraint\RelatedTo('subject'),
]
```

**Comment by JackQiang888** [comment]
Use the above config,

function prepareValidationConstraints in jwt.php
`$configuredConstraints` = $this->getConfiguration()->validationConstraints();

couont array $configuredConstraints  is 0

**Comment by EuclidesJr** [comment]
When I use as suggested I get a Uncaught Error: Class 'Lcobucci\JWT\Validation\Constraint\LooseValidAt'  not found  in my \backend\config\main.php. Did I miss something?

**Comment by bizley** [comment]
And which version of the package are you using?

**Comment by EuclidesJr** [comment]
I am using "bizley/jwt": "3.0"

![image_2021-08-06_170105](https://user-images.githubusercontent.com/10123139/128565016-9853f0f1-d5e3-458f-bad8-512c5ac6f2af.png)

**Comment by EuclidesJr** [comment]
My config file:

`    
'components' => [
        'jwt' => [
            'class' => \bizley\jwt\Jwt::class,
            'signer' => \bizley\jwt\Jwt::HS256,
            'signingKey' => '......',
            'validationConstraints' => [
                new \Lcobucci\JWT\Validation\Constraint\LooseValidAt(
                    new \Lcobucci\Clock\SystemClock(new \DateTimeZone('America/Sao_Paulo')),
                    new \DateInterval('PT1M')
                ),
            ]
        ],
...
]
`

**Comment by bizley** [comment]
`LooseValidAt` was added in `lcobucci/jwt` 4.1 which is used in version 3.1.0 of this package.

**Comment by EuclidesJr** [comment]
Thank you. I updated the version and now it is working

**Comment by koxu1996** [comment]
Setting up `lcobucci/jwt` / `bizley/yii2-jwt` was a painful process for me:
1. Errors were silent or not clear; I had to debug library code to find configuration issues.
2. There are no constraints (validators) configured out-of-the box :crying_cat_face:.

However I finally managed to make it work, so I am sharing code with you guys:

```php
// component configuration
[
    'class' => \bizley\jwt\Jwt::class,
    'signer' => \bizley\jwt\Jwt::RS256,
    'signingKey' => base64_decode("LS0tLS1CRUdJTiBSU0EgUF....."),
    'verifyingKey' => base64_decode("LS0tLS1CRUdJTiBQVUJMS....."),
    'validationConstraints' => function(\bizley\jwt\Jwt $jwt) {
        $signer = $jwt->getConfiguration()->signer();
        $pubKey = $jwt->getConfiguration()->verificationKey();
        $clock = \Lcobucci\Clock\FrozenClock::fromUTC();
        $clock->setTo(new \DateTimeImmutable());
        return [
            new \Lcobucci\JWT\Validation\Constraint\SignedWith($signer, $pubKey),
            new \Lcobucci\JWT\Validation\Constraint\ValidAt($clock),
        ];
    },
]
```

**Comment by bizley** [comment]
Hm, I'm sorry to hear that and I would like to improve it if you could create new issue with that problem and answer at least the questions below:
1. What errors were silent or not clear?
2. What configuration issues did you have?
3. Constraints are done on the lcobucci/jwt side for which this package is only a Yii wrapper - which ones would you like to have configured out-of-the-box and why?
