### ISSUE TITLE
No constraint given

### ISSUE THREAD

**Issue by w4ugit** [bizley/yii2-jwt#27]
**Describe the bug**
No constraint given.
/vendor/bizley/jwt/src/JwtHttpBearerAuth.php:119

**My config**
```
'jwt' => [
            'class' => Jwt::class,
            'signer' => Jwt::HS256,
            'signingKey' => 'hy2#Y3hk4*3j3lf83FJFKmbr%$d3',
        ]
```

**Controller**
```
public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => JwtHttpBearerAuth::class,
            'except' => [
                'options'
            ],
        ];

        return $behaviors;
    }
```

i can't understand why i get this error and how to fix it

**Comment by bizley** [comment]
As I wrote here https://github.com/bizley/yii2-jwt#validating-a-token you need to provide constraints to your token. The linked JWT library, this package is the wrapper of, explains it in details:
 - https://lcobucci-jwt.readthedocs.io/en/stable/issuing-tokens/
 - https://lcobucci-jwt.readthedocs.io/en/stable/validating-tokens/

**Comment by w4ugit** [comment]
i can't figure out where to add it. can you tell me

**Comment by bizley** [comment]
I put it the readme linked above. You can also check some examples in https://github.com/bizley/yii2-jwt/issues/14
I might add some more examples in the readme later on if this causes such problems.

**Comment by w4ugit** [comment]
earned. but now I do not pass the token validation

```
public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => JwtHttpBearerAuth::class,
            'except' => [
                'options'
            ],
        ];

        return $behaviors;
    }
```

I also added the appropriate method loginByAccessToken to the user model (common\models\User), but he does not seem to turn to him
