### ISSUE TITLE
sizeg/yii2-jwt to bizley/yii2-jwt fails to validate \Lcobucci\JWT\Validation\Constraint\SignedWith constraint 

### ISSUE THREAD

**Issue by bologer** [bizley/yii2-jwt#43]
We previously used `sizeg/yii2-jwt` package to manage JWT. Parsing and validation was working fine. During migration to PHP 8.1 we encountered compatibility issues and decided to switched to `bizley/yii2-jwt`. 

Following new package instructions we reconfigured application to match 1 to 1 configuration-wise. Token generation works as expected, however `\Lcobucci\JWT\Validation\Constraint\SignedWith` always produces `Token signature mismatch` exception, which seems to be hash mismatch (found out during debugging). The secret passed properly, I've double checked that. However there is still mismatch. 

Just to give you more insight. We have client application on React, users store JWT via Cookies/LocalStorage. Some of the generated JWT using `sizeg/yii2-jwt` (old package) and when new package is using  `\Lcobucci\JWT\Validation\Constraint\SignedWith` constraint - validation fails. Here is specific place where it fails - (https://github.com/lcobucci/jwt/blob/5.0.x/src/Validation/Constraint/SignedWith.php#L28-L30).

In the old configuration as well in new we used: `HS256` (`Sha256`). 

Old configuration variant looks like this: 
```php
 'jwt' => [
    'class' => '\sizeg\jwt\Jwt',
    'key' => 'secret-key' // HS256 (Sha256) by default
],
```

New variant looks as following: 

```php
'jwt' => [
    'class' => \bizley\jwt\Jwt::class,
    'signer' => \bizley\jwt\Jwt::HS256,
    'signingKey' => [
        'key' => 'secret-key',
        'store' => \bizley\jwt\Jwt::STORE_IN_MEMORY,
        'method' => \bizley\jwt\Jwt::METHOD_PLAIN,
        'passphrase' => '',
    ],
    'validationConstraints' => static function (\bizley\jwt\Jwt $jwt) {
        $config = $jwt->getConfiguration();
        return [
            new \Lcobucci\JWT\Validation\Constraint\SignedWith($config->signer(), $config->signingKey()),
        ];
    }
],
```

Could you please give a hint why this may happen?

**Comment by bizley** [comment]
You linked to the 5.0.x version of lcobucci/jwt which is not released yet but since the code is the same as in 4.2.x it doesn't matter. Unfortunately I don't see a way to help you here. The best solution I could give is to regenerate the tokens with the new library. You could also check the old one with [jwt.io ](https://jwt.io/) to verify the signature. Also please remember that with lcobucci/jwt 4.2 the key you have here is too short and will result in token exception (see my readme for the solution).

Let me know if I can provide any help with this.

**Comment by bologer** [comment]
@bizley thank you for quick feedback. At the end the problem was related to wrong key string used for plain method.
