### ISSUE TITLE
[Q] How to use this lib "validation-only"?

### ISSUE THREAD

**Issue by schmunk42** [bizley/yii2-jwt#49]
We used to use the sizeg lib "validation-only", so actually there's no need for a signer and private key, right?

But configuring a proper signer algorithm is required, and if it's asymetric, you need a key file etc...
So our current workaround is to pass the public key to the signer config, which actually makes no sense.

How do we need to configure the lib to use it only for validation ie. without specifying any private key.

Related discussions: 
- https://github.com/lcobucci/jwt/discussions/720
- https://github.com/lcobucci/jwt/issues/609 [addon]

CC: @amk0 @eluhr @handcode

**Comment by bizley** [comment]
I'm using similar constraints in my [example](https://github.com/bizley/yii2-jwt/blob/master/INSTRUCTION.md). Could you elaborate on what should be added in the docs in your opinion? Thanks for checking this out btw ;)

**Comment by schmunk42** [comment]
I also had 

```
'key' => '',
``` 

but it complained that it can not be an empty string, it needs to be an empty array.

**Comment by bizley** [comment]
I'm reopening to make it possible with 4.0.

**Comment by bizley** [comment]
I've prepared https://github.com/bizley/yii2-jwt/pull/52 to extract JWT tools for a case like that :) Hopefully it's enough.
