### ISSUE TITLE
[Bug] Fails miserably when supplying paths using @app yii aliases

### ISSUE THREAD

**Issue by spmaxinc** [bizley/yii2-jwt#64]
**Describe the bug**
Cannot locate public and private key files when those are entered using @app type Yii aliases. 

`'signingKey' => [
        'key' => '@app/config/keys/id_ecdsa', // path to your PRIVATE key, you can start the path with @ to indicate this is a Yii alias
        'method' => \bizley\jwt\Jwt::METHOD_FILE,
      ],`

Key fails to resolve to an actual path. Path works when spelled out completely. Fix file JwtTools.php line 216. $value should be wrapped in Yii::getAlias($value) in order to resolve yii aliases.

`    if ($method === Jwt::METHOD_FILE) {
      return Signer\Key\InMemory::file(Yii::getAlias($value), $passphrase);
    }
`

**Comment by bizley** [comment]
Oh, I misled everyone, including myself (in the example file), that this would be resolved as an alias in case of array configuration. It was meant to be resolved only if you provide the key as a string. But I'll change it to be resolved always, it's better DX that way. Thank you for reporting.

**Comment by spmaxinc** [comment]
Thank you for a quick fix! 👍
