### ISSUE TITLE
OpenSSL3 Support

### ISSUE THREAD

**Issue by mtangoo** [bizley/yii2-jwt#74]
Followed instruction from: https://github.com/bizley/yii2-jwt/blob/master/INSTRUCTION.md

Making a token, I got infamous `routines::unsupported`

```
[Lcobucci\JWT\Signer\InvalidKeyProvided] Lcobucci\JWT\Signer\InvalidKeyProvided: It was not possible to parse your key, reason:
* error:1E08010C:DECODER routines::unsupported in ...vendor/lcobucci/jwt/src/Signer/InvalidKeyProvided.php:13
Stack trace:
#0 ...vendor/lcobucci/jwt/src/Signer/OpenSSL.php(90): Lcobucci\JWT\Signer\InvalidKeyProvided::cannotBeParsed('\n* error:1E0801...')
```
I understand what it means but I do not know which algos for OpenSSL3  are compatible with this library.

Can you update example as to what is compatible with OSSL3?

**Comment by bizley** [comment]
I can confirm that the example does not work anymore. I will try to update it for v3.

**Comment by mtangoo** [comment]
I have made PR to fix this

**Comment by bizley** [comment]
I'm not sure if secp384r1 is not outdated already in v3 (according to some internet readings). I'm preparing updated example right now, so thank you for the PR but I'll roll with mine.

**Comment by mtangoo** [comment]
>I'm not sure if secp384r1 is not outdated already in v3 (according to some internet readings).

As with most things, OpenSSL have been a kind of esoteric when it comes to documentation. That is the best I could find. The only sure way is to disable legacy provider and test it.

> I'm preparing updated example right now, so thank you for the PR but I'll roll with mine.

as long as the issue get resolved, am all Cheers!

**Comment by bizley** [comment]
https://github.com/bizley/yii2-jwt/releases/tag/4.1.2
